export const FETCH_PLACES_INIT = "FETCH_PLACES_INIT";
export const FETCH_PLACES_START = "FETCH_PLACES_START";

export const FETCH_PLACES_SUCCESS = "FETCH_PLACES";
export const FETCH_PLACES_FAIL = "FETCH_PLACES_FAIL";
export const FETCH_PLACE_BY_ID_INIT = "FETCH_PLACE_BY_ID_INIT";
export const FETCH_PLACE_BY_ID_START = "FETCH_PLACE_BY_ID_START";
export const FETCH_LOCAL_PLACE_BY_ID = "FETCH_LOCAL_PLACE_BY_ID";
export const FETCH_PLACE_BY_ID_SUCCESS = "FETCH_PLACE_BY_ID_SUCCESS";
export const FETCH_PLACE_BY_ID_FAIL = "FETCH_PLACE_BY_ID_FAIL";
export const ADD_PLACE_SUCCESS = "ADD_PLACE_SUCCESS";
export const ADD_REVIEW_SUCCESS = "ADD_REVIEW_SUCCESS";
export const UPDATE_RATING = "UPDATE_RATING";
export const RESET_ADD_PLACE_FORM = "RESET_ADD_PLACE_FORM";
