export const FETCH_PLACES_SUCCESS = "FETCH_PLACES";
export const FETCH_PLACES_FAIL = "FETCH_PLACES_FAIL";
export const FETCH_PLACE_BY_ID_SUCCESS = "FETCH_PLACE_BY_ID_SUCCESS";
export const FETCH_PLACE_BY_ID_FAIL = "FETCH_PLACE_BY_ID_FAIL";
export const ADD_REVIEW = "ADD_REVIEW";
export const MERGE_REVIEWS_BY_ID = "MERGE_REVIEWS_BY_ID";
